### ISSUE TITLE
توضیحات اجرای پروژه 

### ISSUE THREAD

**Issue by MehrdadLinux** [ghobadimhd/email-client#1]
سلام به نظر من اگر توی فایل 
 README.md 
توضیح بنویسید
۱ : پیشنیاز های اجرا چه چیز هایی است
۲ : برای اجرا باید چه کار هایی انجام شود
خیلی خوب میشود

مرسی از شما

**Comment by ghobadimhd** [comment]
فایل 
README.md 
شامل روش نصب و ایجاد فایل تنظیمات اولیه اضافه شد

ممنون
